### ISSUE TITLE
Jdk9 Early Access issue with GenkeyMojo

### ISSUE THREAD

**Issue by nhojpatrick** [mojohaus/keytool#6]
Downloaded Jdk 9 Early Access, wanted to help get maven ready for Java 9.

Installed the Mac installer from, https://jdk9.java.net/download/, specifically Java 9 Build 99 (not jigsaw).

Executing the build the maven-project-info-reports-plugin appears to fail within GenkeyMojo.java as the java version is "9-e" so not correctly resolved to a float.

Console output below from maven.

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey (init) on project maven-project-info-reports-plugin: Execution init of goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey failed: An API incompatibility was encountered while executing org.codehaus.mojo:keytool-maven-plugin:1.0:genkey: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/john/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.0/keytool-maven-plugin-1.0.jar
[ERROR] urls[1] = file:/Users/john/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.jar
[ERROR] urls[2] = file:/Users/john/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: For input string: "9-e"
[ERROR] -> [Help 1]
## org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey (init) on project maven-project-info-reports-plugin: Execution init of goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey failed: An API incompatibility was encountered while executing org.codehaus.mojo:keytool-maven-plugin:1.0:genkey: java.lang.ExceptionInInitializerError: null

realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/john/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.0/keytool-maven-plugin-1.0.jar
urls[1] = file:/Users/john/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.jar
urls[2] = file:/Users/john/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

---

```
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:520)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
## Caused by: org.apache.maven.plugin.PluginExecutionException: Execution init of goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey failed: An API incompatibility was encountered while executing org.codehaus.mojo:keytool-maven-plugin:1.0:genkey: java.lang.ExceptionInInitializerError: null

realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/john/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.0/keytool-maven-plugin-1.0.jar
urls[1] = file:/Users/john/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.jar
urls[2] = file:/Users/john/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

---

```
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:183)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
```
## Caused by: org.apache.maven.plugin.PluginContainerException: An API incompatibility was encountered while executing org.codehaus.mojo:keytool-maven-plugin:1.0:genkey: java.lang.ExceptionInInitializerError: null

realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/john/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.0/keytool-maven-plugin-1.0.jar
urls[1] = file:/Users/john/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.9/plexus-utils-1.4.9.jar
urls[2] = file:/Users/john/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

---

```
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:181)
... 21 more
```

Caused by: java.lang.ExceptionInInitializerError
    at org.codehaus.mojo.keytool.GenkeyMojo.getJDKCommandExe(GenkeyMojo.java:252)
    at org.codehaus.mojo.keytool.GenkeyMojo.getJDKCommandPath(GenkeyMojo.java:245)
    at org.codehaus.mojo.keytool.GenkeyMojo.getKeytoolPath(GenkeyMojo.java:240)
    at org.codehaus.mojo.keytool.GenkeyMojo.execute(GenkeyMojo.java:142)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
Caused by: java.lang.NumberFormatException: For input string: "9-e"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
    at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.lang.Float.parseFloat(Float.java:453)
    at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1117)
    at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:817)
    ... 26 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :maven-project-info-reports-plugin

**Comment by dennisl** [comment]
Hi,

Please try version 1.5 of keytool-maven-plugin. That works for me.

**Comment by tchemit** [comment]
@nhojpatrick any update of this issue for your pb ?

**Comment by nhojpatrick** [comment]
2 years ago I was trying to assist projects get ready for Java 9.

This defect can probably be ignored for another month and then closed as Java 9 instantly becomes and out of support release when Java 10 is released next month.
