### ISSUE TITLE
Create parent directory for generated certificate

### ISSUE THREAD

**Issue by Hugal31** [mojohaus/keytool#9]
For multiple goals, like generateCertificateRequest and generateCertificate, the parent directory of the generated file is not created. I think this is because the method `AbstractKeyToolRequestWithKeyStoreParametersMojo.createParentDirIfNecessary` is never called.

Example:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>keytool-maven-plugin</artifactId>
	<version>1.5</version>
	<executions>
	  <execution>
	    <phase>generate-resources</phase>
	    <id>generateKeyPair</id>
	    <goals>
	      <goal>generateKeyPair</goal>
	    </goals>
	    <configuration>
	      <skipIfExists>true</skipIfExists>
	    </configuration>
	  </execution>
	  <execution>
	    <phase>generate-resources</phase>
	    <id>generateCertificateRequest</id>
	    <goals>
              <goal>generateCertificateRequest</goal>
	    </goals>
	    <configuration>
	      <file>${project.build.directory}/dir1/test.csr</file>
	    </configuration>
	  </execution>
	  <execution>
	    <phase>generate-resources</phase>
	    <id>generateCertificate</id>
	    <goals>
	      <goal>generateCertificate</goal>
	    </goals>
	    <configuration>
	      <infile>${project.build.directory}/dir1/test.csr</infile>
	      <outfile>${project.build.directory}/dir2/test.crt</outfile>
	      <rfc>true</rfc>
	    </configuration>
	  </execution>
	</executions>
	<configuration>
	  <keystore>${project.build.directory}/keystore.jks</keystore>
	  <storepass>storepass</storepass>
	  <keypass>storepass</keypass>
	  <alias>test</alias>
	  <validity>100</validity>
	  <sigalg>SHA1withRSA</sigalg>
	  <keyalg>RSA</keyalg>
	  <dname>cn=com.example</dname>
	</configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

Output:
```
> mvn package -X
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.8.0-58-generic", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- keytool-maven-plugin:1.5:generateKeyPair (generateKeyPair) @ test ---
[INFO] 
[INFO] --- keytool-maven-plugin:1.5:generateCertificateRequest (generateCertificateRequest) @ test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.108 s
[INFO] Finished at: 2017-08-01T09:50:46+02:00
[INFO] Final Memory: 9M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.5:generateCertificateRequest (generateCertificateRequest) on project test: Failed executing '/bin/sh -c cd /tmp/test && /usr/lib/jvm/java-8-openjdk-amd64/jre/../bin/keytool -certreq -keystore /tmp/test/target/keystore.jks -'*****' '*****' -alias test -sigalg SHA1withRSA -file /tmp/test/target/dir1/test.csr -keypass '*****' -dname cn=com.example' - exitcode 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.5:generateCertificateRequest (generateCertificateRequest) on project test: Failed executing '/bin/sh -c cd /tmp/test && /usr/lib/jvm/java-8-openjdk-amd64/jre/../bin/keytool -certreq -keystore /tmp/test/target/keystore.jks -'*****' '*****' -alias test -sigalg SHA1withRSA -file /tmp/test/target/dir1/test.csr -keypass '*****' -dname cn=com.example' - exitcode 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed executing '/bin/sh -c cd /tmp/test && /usr/lib/jvm/java-8-openjdk-amd64/jre/../bin/keytool -certreq -keystore /tmp/test/target/keystore.jks -'*****' '*****' -alias test -sigalg SHA1withRSA -file /tmp/test/target/dir1/test.csr -keypass '*****' -dname cn=com.example' - exitcode 1
	at org.codehaus.mojo.keytool.AbstractKeyToolRequestMojo.consumeResult(AbstractKeyToolRequestMojo.java:196)
	at org.codehaus.mojo.keytool.AbstractKeyToolRequestMojo.execute(AbstractKeyToolRequestMojo.java:130)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tchemit** [comment]
Closed by #10. thanks for report
